export const FETCH_PRACTITIONERS_BEGIN = "FETCH_PRACTITIONERS_BEGIN";
export const FETCH_PRACTITIONERS_SUCCESS = "FETCH_PRACTITIONERS_SUCCESS";
export const FETCH_PRACTITIONERS_FAILURE = "FETCH_PRACTITIONERS_FAILURE";
export const EDIT_PRACTITIONER = "EDIT_PRACTITIONER";
export const UPDATE_PRACTITIONER = "UPDATE_PRACTITIONER";